name: Build TWRP Recovery

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip python3

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=~/bin:$PATH" >> $GITHUB_ENV

      - name: Initialize TWRP manifest
        run: |
          mkdir ~/twrp && cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -c --no-tags --no-clone-bundle -j$(nproc)

      - name: Clone device tree
        run: |
          cd ~/twrp
          git clone https://github.com/killshotxd/lexus_bringup_twrp.git device/oneplus/lexus

      - name: Build recovery image
        run: |
          cd ~/twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          . build/envsetup.sh
          lunch twrp_lexus-eng
          mka recoveryimage -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: twrp-lexus-recovery
          path: ~/twrp/out/target/product/lexus/recovery.img
